<div class="page-title">
    <h1>
        <?php echo $this->__('My Tickets') ?>
    </h1>

    <span><a href="<?php echo $this->getUrl('inchoo_ticket/ticket/newTicket') ?>" class="btn-add">Create Ticket</a></span>
</div>

<?php
    $tickets = $this->getCollection();

    if ($tickets->count() > 0) {
?>
    <table class="data-table" id="my-tickets-table">
        <thead>
            <tr>
                <th><?php echo $this->__('Ticket ID #') ?></th>
                <th><?php echo $this->__('Subject') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Status') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($tickets as $ticket): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->getUrl('inchoo_ticket/ticket/ticket') ?>id/<?php echo $ticket->getId() ?>">
                        #<?php echo $this->escapeHtml($ticket->getId()) ?>
                    </a>
                </td>
                <td><?php echo $this->escapeHtml($ticket->getSubject()) ?></td>
                <td><?php echo date("D, j M, Y", strtotime($ticket->getTimestamp())) ?></td>
                <td>
                    <?php echo ($ticket->getStatus() == 1 ? 'Resolved' : 'Open') ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>

    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php } else { ?>
        <p><?php echo $this->__('No tickets just yet.'); ?></p>
<?php } ?>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>